### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by michiel75** [watchforstock/evohome-client#10]
Hello I am running the Python script on a CentOS7 server with python and your evo home package installed
I get the following error in debug mode, do you have any idea can be the cause, I can login with used credentials on https://europe.mytotalconnectcomfort.com/

Thnx

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): rs.alarmnet.com
send: b'POST /TotalConnectComfort/Auth/OAuth/Token HTTP/1.1\r\nHost: rs.alarmnet.com\r\nContent-Length: 307\r\nUser-Agent: python-requests/2.7.0 CPython/3.3.2 Linux/3.10.0-042stab092.3\r\nContent-Type: application/x-www-form-urlencoded\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml\r\nAuthorization: Basic YjAxM2FhMjYtOTcyNC00ZGJkLTg4OTctMDQ4YjlhYWRhMjQ5OnRlc3Q=\r\n\r\nPragma=no-cache&Password=Password25&Content-Type=application%2Fx-www-form-urlencoded%3B+charset%3Dutf-8&Cache-Control=no-store+no-cache&Host=rs.alarmnet.com%2F&Connection=Keep-Alive&Username=Username&scope=EMEA-V1-Basic+EMEA-V1-Anonymous+EMEA-V1-Get-Current-User-Account&grant_type=password'
reply: 'HTTP/1.1 200 OK\r\n'
DEBUG:requests.packages.urllib3.connectionpool:"POST /TotalConnectComfort/Auth/OAuth/Token HTTP/1.1" 200 1326
header: Cache-Control header: Pragma header: Content-Length header: Content-Type header: Expires header: Server header: X-Powered-By header: Date Traceback (most recent call last):
  File "getTemp.py", line 5, in <module>
    client = EvohomeClient('username', 'password', debug=True)
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/evohomeclient2/**init**.py", line 18, in **init**
    self._login()
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/evohomeclient2/__init__.py", line 69, in _login
    self.access_token = self._convert(r.text)['access_token']
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/evohomeclient2/base.py", line 32, in _convert
    return json.loads(self.reader(object)[0])
  File "/opt/rh/python33/root/usr/lib64/python3.3/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'str' does not support the buffer interface

**Comment by zxdavb** [comment]
I would close this, given the tyranny of time, and recent PRs.
