### ISSUE TITLE
Issue durring  adding repository.

### ISSUE THREAD

**Issue by art8814** [watchforstock/evohome-client#107]
Hello, durring adding this repo to my Home Assistant i getting this error:

> ERROR (MainThread) [hassio.utils.json] Can't read json from /data/addons/git/b3e07dba/repository.json: [Errno 2] No such file or directory: '/data/addons/git/b3e07dba/repository.json

Am I doing something wrong ? I have to admit that I'm noob ;-)

**Comment by zxdavb** [comment]
@art8814 Home Assistant doesn't use this library any more - it uses [evohome-async](https://github.com/zxdavb/evohome-async) instead. The [HA documentation](https://www.home-assistant.io/integrations/evohome) will be corrected in the next release of HA.

In any case, you shouldn't have to 'add' any evohome repo to HA - just adding the correct data to HA's **configuration.yaml** file will cause the correct package to be downloaded from pypi.org:
```yaml
evohome:
  username: YOUR_USERNAME
  password: YOUR_PASSWORD
```

If you are stuck, ask for help at: https://community.home-assistant.io/

@watchforstock, I think you can close this issue.
