### ISSUE TITLE
ImportError : No module named "location"

### ISSUE THREAD

**Issue by sander76** [watchforstock/evohome-client#11]
Installing in a virtualenv.

Installing through pip following your documentation doesn't work. It expects : "version spc in ./evohome-client"

python setup.py install works, but then
File "C:\data\envs\honeywell\lib\site-packages\evohomeclient-0.2.0-py3.4.egg\evohomeclient2\__init__.py", line 5, in <module>
ImportError: No module named 'location'

**Comment by watchforstock** [comment]
This is a bit strange as I've not had (or heard of) problems installing it via pip before, including in a virtualenv. Have you tried making sure pip is up to date? I've seen the odd reference to that error related to out of date pip installs (e.g. http://stackoverflow.com/questions/28502283/valueerror-expected-version-spec-when-installing-local-wheel-via-pip).

The location.py file should be installed next to the __init__.py file that's causing your error so could you check whether or not that's there?

Thanks

**Comment by sander76** [comment]
I'll recheck. After I got it working by manually changing references using full path locations I found out it is not python 3 compatible. So possibly the error lies there?

**Comment by watchforstock** [comment]
I think your PR covers this too
