### ISSUE TITLE
Current thermostat status?

### ISSUE THREAD

**Issue by martin3000** [watchforstock/evohome-client#112]
Is it possible to see the status fo the thermostat, if is currently on or off?
client.locations[0].status() only shows 
`{'locationId': '2161422', 
'gateways': [{'gatewayId': '959681', 'temperatureControlSystems': [{'systemId': '168563', 'zones': [{'zoneId': '168564', 'temperatureStatus': {'temperature': 23.0, 'isAvailable': True}, 'activeFaults': [], 'setpointStatus': {'targetHeatTemperature': 23.0, 'setpointMode': 'TemporaryOverride', 'until': '2020-09-25T17:00:00Z'}, 'name': 'THERMOSTAT'}], 'activeFaults': [], 'systemModeStatus': {'mode': 'Heat', 'isPermanent': True}}], 
'activeFaults': []}]}
`

**Comment by watchforstock** [comment]
Not that I'm aware of. The best you can do it get the current temperature and the target temperature and assume that if the current < target then it's attempting to heat.

**Comment by zxdavb** [comment]
@martin3000 I am not sure exactly what you mean. The thermostat has no 'on' or 'off' - either the temperature it is measuring is above it's setpoint or not.

However, actuators (e.g. a TRV) do *call for heat* - so they can be 'on' - they will also have a *demand* from 0-100%.

The relay controlling the heat source (e.g. a gas boiler, or a communal heat source) will also be 'on' or 'off', at a relative ratio determined by heat demand, cycle rate, dead bands, optimizations etc.

None of this information (call for heat, heat demand) is exposed by the vendor's RESTful API (either version) and it is impossible to reliably 'emulate' this data using the data that _is_ available via the API - I have tried.

However, you can do it by eavesdropping the RF protocol that these devices use to speak with each other, see: https://github.com/zxdavb/evohome_rf

This package is for Python, and a Home Assistant integration is in play, and something similar exists for Domoticz.

**Comment by martin3000** [comment]
Thank you both!
