### ISSUE TITLE
Master branch version

### ISSUE THREAD

**Issue by RichieB2B** [watchforstock/evohome-client#115]
The version in setup.py for the master branch is 0.3.4 but https://pypi.org/project/evohomeclient/ is at 0.3.7 which exists only as a tag in this GitHub repo. This confuses me. Is master ahead of 0.3.7 or is 0.3.7 ahead of master?

**Comment by watchforstock** [comment]
Master will always be the latest. It does seem that the setup.py hasn't been updated along with the tags (which I'm slightly surprised at, but appears to be the case!)

**Comment by RichieB2B** [comment]
Ok, thanks.
