### ISSUE TITLE
ECO/BOOST function

### ISSUE THREAD

**Issue by JanvdW304** [watchforstock/evohome-client#119]
Evohome has some predefined quick functions/ presets, like Day Off, Away, Eco/Boost, which are implemented in the Domoticz Evohome client.

The problem with this function is that it sets the temperature in all rooms to 15 degrees, even in rooms with a lower temperature that don't need to heat up. I would really like to have a 'relative Away' function: a function that lowers the temperature in all zones a few (e.g. 3) degrees.

**Comment by watchforstock** [comment]
While I totally agree with your concept, I'm afraid you'd need to raise it with Honeywell - this library is not associated with Honeywell so the contributors cannot directly help. Your alternative would be to code some sort of custom mode which overrides all of the rooms with programmes according to your logic above.
