### ISSUE TITLE
heat demand per zone

### ISSUE THREAD

**Issue by ruliezz** [watchforstock/evohome-client#123]
In the Evohome control panel, you can see the heat demand per zones. Is it possible to get this data by the API and view this information in the Domoticz web interface?

**Comment by watchforstock** [comment]
Unfortunately this information doesn't appear to make it into the API responses so isn't available. If Honeywell change it so it appears in the app then we would be able to access it.

**Comment by ruliezz** [comment]
Thanks, Is it possible for you to ask this request to Honeywell? Perhaps they are able to implemented for us :-)

**Comment by zxdavb** [comment]
@ruliezz Resideo (who hived off from Honeywell) is not likely going to implement this feature - they have been asked many times before.

However, you can get this data using a USB-to-RF dongle, and code like: https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584

**Comment by raldred** [comment]
When you say you can see heat demand in the panel, what are you referring to?
Mine only shows the room temp, target temp and if the target is an override.

**Comment by zxdavb** [comment]
It is a hidden feature: you can get at it by a long press on the setting button.

**Comment by raldred** [comment]
I've never seen that before! It would be quite nice to graph the data from that.
Thanks for sharing.

**Comment by dmsviento** [comment]
+1 for this api request from Resideo/honywell. Without knowing heating demand on the boiler most analysis can't really be put into context. I guess I'll also message Resideo.
@watchforstock many thanks for the great work on this project.

**Comment by raldred** [comment]
@dmsviento I've since moved to using home assistant with an evofw3 usb device.

By evesdropping on the raw rf traffic in home assistant with [ramses_rf](https://github.com/zxdavb/ramses_rf?tab=readme-ov-file) you can gather the heat demand data which isnt available on the official api.

**Comment by watchforstock** [comment]
Closing as not available through the API this library consumes
