### ISSUE TITLE
removed from pypi ?

### ISSUE THREAD

**Issue by sander76** [watchforstock/evohome-client#13]
I am trying to integrate your client in home assistant.
https://home-assistant.io/

It requires your library to be installable from pypi. It appears it doesn't (anymore). 
Are you able to fix this ?

**Comment by watchforstock** [comment]
The library has never been on Pypi. You should be able to install it directly and it then be available to home assistant. I'll try and take a look at adding it to pypi, but haven't done this before so it may take a bit. If you have any experience happy to have help!

**Comment by sander76** [comment]
I have no experience. Sorry. But willing to try myself. I was under the wrong impression it was on pypi as on the docs it says pip install...

For home assistant: it automatically pulls from pypi. So another approach would break installation logic.

**Comment by watchforstock** [comment]
OK I've found a guide on doing this so will try to do it tonight. Are you writing a wrapper for home assistant? It looks like a good tool and I'd be interested in linking evohome to it too...

**Comment by watchforstock** [comment]
Easier than I thought. You should now be able to do `pip install evohomeclient`

**Comment by sander76** [comment]
Thanks !
I have followed Home Assistant for some time and last week I made the jump.
Right now I am getting familiar with the system setting up all the basics. Implementing evohome is my next step...
