### ISSUE TITLE
homeassistant.components.thermostat: Error while setting up platform honeywell

### ISSUE THREAD

**Issue by dels78** [watchforstock/evohome-client#21]
Spoke with @rmkraus on gitter to debug, and he believes it may be related to an API change on the Honeywell part, can someone look at it please? Thanks!

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 145, in _setup_platform
    self.hass, platform_config, self.add_entities, discovery_info)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/thermostat/honeywell.py", line 35, in setup_platform
    for i, zone in enumerate(zones):
  File "/home/pi/.homeassistant/lib/evohomeclient/__init__.py", line 73, in temperatures
    self._populate_full_data(force_refresh)
  File "/home/pi/.homeassistant/lib/evohomeclient/__init__.py", line 33, in _populate_full_data
    userId = self.user_data['userInfo']['userID']
TypeError: list indices must be integers, not str

**Comment by watchforstock** [comment]
I've just tested this here and it's working for me. 

Could you add the line "print(self.user_data)" before the bottom reference line (so inserting before line 33 in "/home/pi/.homeassistant/lib/evohomeclient/__init_.py"? That way we should be able to find out what the response is that's coming back from the server for you - obviously remove any sensitive information from the content.

If that doesn't work then we can probably come up with a separate script you could run to track this down.

**Comment by dels78** [comment]
16-01-07 19:28:46 homeassistant.components.thermostat: Error while setting up platform honeywell
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 145, in _setup_platform
    self.hass, platform_config, self.add_entities, discovery_info)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/thermostat/honeywell.py", line 35, in setup_platform
    for i, zone in enumerate(zones):
  File "/home/pi/.homeassistant/lib/evohomeclient/__init__.py", line 74, in temperatures
    self._populate_full_data(force_refresh)
  File "/home/pi/.homeassistant/lib/evohomeclient/__init__.py", line 34, in _populate_full_data
    userId = self.user_data['userInfo']['userID']
TypeError: list indices must be integers, not str

same thing, I also tried putting it right after the if statement that populates it and it stops at the same time.

A couple things I noticed while going through that though is there are 2 evohomeclient folders that get created.

ll | grep evo
drwxr-xr-x 3 pi pi  4096 Jan  7 19:37 evohomeclient
drwxr-xr-x 2 pi pi  4096 Jan  7 19:37 evohomeclient-0.2.4.dist-info
drwxr-xr-x 3 pi pi  4096 Jan  7 19:37 evohomeclient2

the first one only has 3 files:
ll
total 20
-rw-r--r-- 1 pi pi 8297 Jan  7 19:37 __init__.py
drwxr-xr-x 2 pi pi 4096 Jan  7 19:37 __pycache__
-rw-r--r-- 1 pi pi  142 Jan  7 19:37 test.py

the second has that:

**Comment by dels78** [comment]
The more I look at it (I have opened the evohomeclient/test.py) file and I believe the problem is the two directories... I also think I saw your own credentials, you may want to update/change them and update the repo to remove it?

**Comment by RamboRogers** [comment]
I'm getting the same error:
hass@hood:~/.homeassistant$ tail home-assistant.log
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 145, in _setup_platform
    self.hass, platform_config, self.add_entities, discovery_info)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/thermostat/honeywell.py", line 35, in setup_platform
    for i, zone in enumerate(zones):
  File "/home/hass/.homeassistant/lib/evohomeclient/__init__.py", line 73, in temperatures
    self._populate_full_data(force_refresh)
  File "/home/hass/.homeassistant/lib/evohomeclient/__init__.py", line 33, in _populate_full_data
    userId = self.user_data['userInfo']['userID']
TypeError: list indices must be integers, not str
hass@hood:~/.homeassistant$

**Comment by watchforstock** [comment]
Thanks @RamboRogers . I'm still struggling to replicate it here - are you able to add the print line in as I said above?

"Could you add the line "print(self.user_data)" before the bottom reference line (so inserting before line 33 in "/home/pi/.homeassistant/lib/evohomeclient/__init_.py"? That way we should be able to find out what the response is that's coming back from the server for you - obviously remove any sensitive information from the content."

For you it would be in /home/hass/.homeassistant/lib/evohomeclient/__init_.py. Seeing the data coming back from that call would let me try and work out what's going on

Thanks

**Comment by dels78** [comment]
As I said before, I get the same thing when I add the print...

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 145, in _setup_platform
    self.hass, platform_config, self.add_entities, discovery_info)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/thermostat/honeywell.py", line 35, in setup_platform
    for i, zone in enumerate(zones):
  File "/home/pi/.homeassistant/lib/evohomeclient/__init__.py", line 74, in temperatures
    self._populate_full_data(force_refresh)
  File "/home/pi/.homeassistant/lib/evohomeclient/__init__.py", line 34, in _populate_full_data
    userId = self.user_data['userInfo']['userID']
TypeError: list indices must be integers, not str

**Comment by RamboRogers** [comment]
I've actually uninstalled homeassistant, it didn't work with my thermostat and I couldn't get it to work with my serial controller from MySensors.org.   I got super frustrated and just loaded MyController.org and everything is now working.  It's not nearly as nice as hass though, I with the debug info were better.  I added things to the YAML and you can't ever tell what the current state of hass is.

**Comment by watchforstock** [comment]
Thanks @dels78 - the output must be going somewhere else that would let me track it down.

Instead of just the print() line, could you put in:

    with open('/tmp/evohomedebug.json', 'w') as output_file:
        import json
        output_file.write(json.dumps(self.user_data))

That should cause the output to appear in the /tmp directory. Hopefully we can track this down and fix it!

**Comment by dels78** [comment]
Hrm... 

[{"code": "EmailOrPasswordIncorrect", "message": "The email or password provided is incorrect."}]

But when I connect directly to mytotalconnectcomfort.com it works great... any way I can test my  user/password against the API directly? I tried goofing around with a Chrome extension, but my attempt at formulating a proper JSON call was a failure heh.

Thanks for the help.

**Comment by watchforstock** [comment]
@dels78 Bit of a long shot, but where are you based? The API I'm accessing has EMEA in a number of places so if your account was based somewhere else that might account for it being unrecognised.

As for a direct JSON call, you need to POST to: https://rs.alarmnet.com/TotalConnectComfort/WebAPI/api/Session

Set "content-type" header to "application/json"

Post the following JSON object:
    {
      "Username":"<username",
      "Password":"<password>",
      "ApplicationId":"91db1612-73fd-4500-91b2-e63b069b185c"
    }

That should give you the user_data response.

**Comment by dels78** [comment]
@watchforstock Well, I believe your long shot may be right... I am located in the US and I tried to post raw to the application and I got this :

[
  {
    "code": "EmailOrPasswordIncorrect",
    "message": "The email or password provided is incorrect."
  }
]

Where did you get the application id from? It would seem stupid that there is no US API, but you never know I guess...

**Comment by watchforstock** [comment]
OK so we haven't solved the problem, but at least we've made progress! I think there is a US API, but I reverse engineered this one from the Total Comfort Connect Europe application - we have to sign up via a different site to the US one. Interestingly, the forum where we've been discussing the API has just had some messages from a US member of staff, so it may be worth asking the question in there (see http://www.automatedhome.co.uk/vbulletin/showthread.php?3863-Decoded-EvoHome-API-access-to-control-remotely&p=25291#post25291). I'm happy to extend the API to support US users as well - it's obviously just more difficult for me to test as my system is on the European side.

**Comment by watchforstock** [comment]
@dels78 There appears to be some interest from Honeywell in opening up the US API, based on an exchange on the forums. Can you tell me what Honeywell device you're trying to use with Home Assistant / the API? I'm not sure whether it'll make a difference or not, but thought I'd check.

**Comment by dels78** [comment]
@watchforstock I'm on my way home from work, I will reply when I get there! Thank you for the help!

**Comment by dels78** [comment]
@watchforstock 
This is the one (I have two of them, that I am able to control with the Total Connect Comfort app, website and also IFTTT):
http://author-yourhome.honeywell.com/en/products/thermostat/wireless-focuspro-comfort-system

**Comment by kk7ds** [comment]
I think you can close this as the US API for honeywell is completely different and supported by another library. HA has been fixed.

**Comment by dels78** [comment]
Thanks @kk7ds, do you have more details on "HA has been fixed"? Do you mean just update the honneywell component or something else?

Thanks for the help!

**Comment by kk7ds** [comment]
Sure, there were a bunch of patches, but a clean one to look at is this:

https://github.com/balloob/home-assistant/blob/0fbd947426c7d83c6fcbe9af80b75196dc06106e/homeassistant/components/thermostat/honeywell.py#L182-L236

I also added tests for the evohomeclient based platform in HA:

https://github.com/balloob/home-assistant/commit/0fbd947426c7d83c6fcbe9af80b75196dc06106e

Eyes on those to make sure they're reasonable would be great too.

**Comment by anarro** [comment]
Hi, I'm a user outside US, i live in Spain (Europa), now I can't connect with my Honeywell device.. can you help us please?, It's a problem of Honeywell's servers?

Thank you very much..

**Comment by anarro** [comment]
Hi,

I updated HA and now works fine (v. 19.2)..

**Comment by cuesight** [comment]
I'm struggling to get HA to control my two thermostats.  I can SEE them, but can't seem to CHANGE them.  Is there some place I can go to try to figure out why?  Thanks.

**Comment by watchforstock** [comment]
Closing as original issue was fixed in Home assistant. Other issues should be opened as new tickets please.
