### ISSUE TITLE
Info about setting temperature

### ISSUE THREAD

**Issue by nico81** [watchforstock/evohome-client#22]
This is not an issue, is it possible to set temperature until the next schedule?
Thanks, your client rocks!!!

**Comment by sander76** [comment]
Good one... like to know that too...

**Comment by watchforstock** [comment]
I haven't seen anything that would do this. You could have the same effect by retrieving the programme for that zone and then overriding it until the next scheduled change. Would work but with more work...

**Comment by nico81** [comment]
Ok, thanks!
