### ISSUE TITLE
SSL certificate failed..

### ISSUE THREAD

**Issue by sander76** [watchforstock/evohome-client#23]
All of a sudden I get a SSL error (It used to work perfectly.):

```
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)
```

Any idea how to solve this ?

**Comment by nico81** [comment]
Yes, follow these instructions (and following messages), pay attention to get the right certificate.
http://www.automatedhome.co.uk/vbulletin/showthread.php?3863-Decoded-EvoHome-API-access-to-control-remotely&p=25095&viewfull=1#post25095

**Comment by sander76** [comment]
Thanks! But this morning I powered up my rpi and all is working without changing a thing. I guess Honeywell has solved it?

**Comment by nico81** [comment]
I tried to remove the certificate on my RPI, the issue seems gone, but if I keep the certificate the response is faster

**Comment by watchforstock** [comment]
It sounds like Honeywell has fixed this. If it happens again (or often) then we can look at adding an option to skip checking the certificates
