### ISSUE TITLE
Data no longer refreshed after Total Connect Comfort server update

### ISSUE THREAD

**Issue by Erik-MG** [watchforstock/evohome-client#25]
Issue fixed after a restart -- sorry and thanks for this piece of coding. Works very well!

This morning there was a planned outage for the Total Connect Comfort web server. However, after the server came back online again I don't see my Evohome information updated using the evohome-client2 script. Could i.et be the server can't be reached anymore? Has Honeywell switched to another server?
The iOS app is updating itself with the latest info via the Toal Connect Comfort server as before.

**Comment by watchforstock** [comment]
Closing as sounds like this was a temporary issue.
