### ISSUE TITLE
Not able to connect to Controller

### ISSUE THREAD

**Issue by Safritjuh** [watchforstock/evohome-client#28]
Hi,

I've installed the evohome client etc etc..
When I want to initialize the controller I get the error "evohome hardware not found".
Is this on the Domoticz side or Honeywell side?

**Comment by Safritjuh** [comment]
It seems to be something with python from my guess.. as the variables (%s) are not parsed form some reason.

**Comment by watchforstock** [comment]
That error message doesn't come from this library, so I suspect it's on the Domoticz side - I'd see if their forums can help you narrow it down.
