### ISSUE TITLE
External Temperature - is it reported somewhere

### ISSUE THREAD

**Issue by rjclocks** [watchforstock/evohome-client#29]
I am trying to extract the external temperature as reported in the raw evohome json data (weather.temperature). I cannot see a function in this API which returns it. Is there one that I am missing?

**Comment by watchforstock** [comment]
Unfortunately I don't think so. If I remember correctly, the app goes directly to an external service to collect the external temperature - it doesn't come through the honeywell API. If you want API access to weather data, weather underground is often a good source and from memory free if you don't make large numbers of calls each day
