### ISSUE TITLE
Away mode wrong in Home Assistant

### ISSUE THREAD

**Issue by TooUnCool** [watchforstock/evohome-client#30]
Away mode isn't being represented in Home Assistant. The entire house is set to Away via a Quick Action, but in HA the "Away" flag is not set on any zone.

Is it something I am doing wrong or is it a 'feature'?

![ha_evohome_awaymode](https://cloud.githubusercontent.com/assets/19999073/18902956/2e2987b0-854e-11e6-9c4b-63df1d4626b5.PNG)

Advice appreciated!

**Comment by zxdavb** [comment]
This issue is being addressed with a new HA component, see here:
https://community.home-assistant.io/t/honeywell-evohome-thermostat-work-started-need-advice/43740/15

**Comment by zxdavb** [comment]
I would close this - it is an issue with teh HA component, rather than **evohome-client**.
