### ISSUE TITLE
Question: Will I be able to see all radiator valves seperatly when using evohome with HA?

### ISSUE THREAD

**Issue by butsjoh** [watchforstock/evohome-client#32]
Not clear to me if i would be able to control each radiator valve in a evohome zone seperatly after using it in home assistant. Could you explain how it works? Thnx

**Comment by watchforstock** [comment]
Yes you should be able to. It should add a separate device for each zone.

**Comment by butsjoh** [comment]
Hmmm just close without reply :(

**Comment by butsjoh** [comment]
Sorry ignore my last comment, github design seems broken on safari ios . Thnx for reply 👍
