### ISSUE TITLE
Error message on Evohome-client version2

### ISSUE THREAD

**Issue by sanman74** [watchforstock/evohome-client#33]
The evohome-client v2 not working (v1 is working properly) with hungarian mytotalconnectcomfort account

Debug log:
 --------------------------------------------------------------------------------------------
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): tccna.honeywell.com
send: 'POST /Auth/OAuth/Token HTTP/1.1\r\nHost: tccna.honeywell.com\r\nContent-Length: 299\r\nAccept-Encoding: gzip, deflate, compress\r\nAccept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml\r\nUser-Agent: python-requests/2.2.1 CPython/2.7.6 Linux/3.4.0+\r\nContent-Type: application/x-www-form-urlencoded\r\nAuthorization: Basic YjAxM2FhMjYtOTcyNC00ZGJkLTg4OTctMDQ4YjlhYWRhMjQ5OnRlc3Q=\r\n\r\nUsername=xxx%40gmail.com&Host=rs.alarmnet.com%2F&Password=x&Pragma=no-cache&Cache-Control=no-store+no-cache&scope=EMEA-V1-Basic+EMEA-V1-Anonymous+EMEA-V1-Get-Current-User-Account&grant_type=password&Content-Type=application%2Fx-www-form-urlencoded%3B+charset%3Dutf-8&Connection=Keep-Alive'
DEBUG:urllib3.connectionpool:Setting read timeout to None
reply: 'HTTP/1.1 200 OK\r\n'
header: Set-Cookie: tccna=R3708284716; path=/; expires=Sun, 27-Nov-2016 20:47:39 GMT
header: Cache-Control: no-cache
header: Pragma: no-cache
header: Content-Length: 1433
header: Content-Type: application/json;charset=UTF-8
header: Expires: -1
header: Server: Microsoft-IIS/8.5
header: X-Powered-By: ASP.NET
header: Server: Web1
header: Date: Sat, 26 Nov 2016 20:32:30 GMT
DEBUG:urllib3.connectionpool:"POST /Auth/OAuth/Token HTTP/1.1" 200 1433
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): tccna.honeywell.com
send: 'GET /WebAPI/emea/api/v1/userAccount HTTP/1.1\r\nHost: tccna.honeywell.com\r\nAccept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml\r\napplicationId: b013aa26-9724-4dbd-8897-048b9aada249\r\nAccept-Encoding: gzip, deflate, compress\r\nAuthorization: bearer mSSULMOtRu5F8CU2xIiw1J29TSC1AsIP3E4ertq2mMubpb6B5jgks6DvKYej1dG4WPBXqzPgw87rPUJz1zSm0UZSFDTR4y4janGuVhX_dfrtzhh-MOHOXCqfCrtzyQ7tJQL1dsjrTKibU_5wHAZarFytnJ10duo9pbY26RM-xUH1aAP_w0QuhJ1OsOVHdJFY8m_susY5qkaYkQeSzFFZeedqgUtWOa2I_YTsS1r6msq0OXGKBCcqw1tv8PK0-nwTgPshwh7pfL7PRA3U9JlfrxADHOY8s30PBvNai69Vq-L-
qgUtWOa2I_YTsS1r6msq0OXGKBCcqw1tv8PK0-nwTgPshwh7pfL7PRA3U9JlfrxADHOY8s30PBvNai69Vq-L-qJF3BCfiHGJo_SmVFhjPFwS6vLeL0NYjTfIHXSjA1Kz3Jt83q4RNRL4E20zMg110rsLgALF-XMXp0Udjf7tuoaBJ0O1EU4VrtG-BpsGnc5LFN2BvPRZVdKZAgD_gcEvuQ48tZsgy2soyHp-eIg8rSroBKMKIpIRE3UvphDB-8hNUYCHIJCZkSlIW9RY9h3OyI1gwlpBGcqvPZjcdYQGQWpda6052CV5ts2dcEV2TFEPwgf5rOprQkKH628p_BiABRSJGAlzbjw3GHho4_Au-yCsrtzbQ6iwenHX2QPurDTUeTxufoWRLwjLSdg8ABGWFvEBCxPGG0R-zBfGrDmhDZ0rw\r\nUser-Agent: python-requests/2.2.1 CPython/2.7.6 Linux/3.4.0+\r\n\r\n'
DEBUG:urllib3.connectionpool:Setting read timeout to None
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Set-Cookie: tccna=R3710656558; path=/; expires=Sun, 27-Nov-2016 20:47:39 GMT
header: Cache-Control: no-cache
header: Pragma: no-cache
header: Content-Type: application/json; charset=utf-8
header: Expires: -1
header: Server: Microsoft-IIS/8.5
header: X-AspNet-Version: 4.0.30319
header: X-Powered-By: ASP.NET
header: Server: Web1
header: Date: Sat, 26 Nov 2016 20:32:31 GMT
header: Content-Length: 167
DEBUG:urllib3.connectionpool:"GET /WebAPI/emea/api/v1/userAccount HTTP/1.1" 400 167
Traceback (most recent call last):
  File "evozone2.py", line 2, in <module>
    client = EvohomeClient('xxx@gmail.com','x', debug=True)
  File "/usr/local/lib/python2.7/dist-packages/evohomeclient2/__init__.py", line 18, in __init__
    self._login()
  File "/usr/local/lib/python2.7/dist-packages/evohomeclient2/__init__.py", line 76, in _login
    self.installation()
  File "/usr/local/lib/python2.7/dist-packages/evohomeclient2/__init__.py", line 86, in installation
    r = requests.get('https://tccna.honeywell.com/WebAPI/emea/api/v1/location/installationInfo?userId=%s&includeTemperatureControlSystems=True' % self.account_info['userId'], headers=self.headers)
TypeError: list indices must be integers, not str

**Comment by voldzi** [comment]
the same for me... (CZ account)

**Comment by andreadodo** [comment]
me too!

**Comment by voldzi** [comment]
Thanks for tip but it doesn't work either :-(  (error: exceptions.HTTPError: 400 Client Error: Bad Request)

**Comment by watchforstock** [comment]
Definitely still working in the UK. I've just tried debugging the latest app here. I can see that applicationId has changed. Perhaps you could try changing the variable here: https://github.com/watchforstock/evohome-client/blob/master/evohomeclient2/__init__.py#L72 and setting it to the value "31875b94-09d4-4f03-a8f8-727c48179fa5"

I'm assuming that your log in credentials are correct, that's probably the most often issue. 

If the above still doesn't work, we might need to see about adding some debugging information to narrow the error down further.

**Comment by voldzi** [comment]
Change the applicatinId produce the same error:-( ...btw I registered here (honeywell application works great): https://international.mytotalconnectcomfort.com NOT here http://www.mytotalconnect.com ...

**Comment by voldzi** [comment]
So it works only for UK :-( ...I had to choose a different device...
