### ISSUE TITLE
Cancelling temperature overrides in v2

### ISSUE THREAD

**Issue by paulg1** [watchforstock/evohome-client#34]
This is a great library. Thanks for developing it! I have a couple of questions.

Is it possible to cancel zone temperature overrides in the v2 API? I find the v1 API function is very slow and can be unreliable, in that it either hangs or the last one or two zones don't get cancelled.

Also, does the v2 client.temperatures() cache values or return updated values on every call? There is no force_refresh=True parameter option as with the v1 call.

**Comment by watchforstock** [comment]
Hi,

If you have a zone object, you should be able to call cancel_temp_override() to remove the override.

The v2 client.temperatures() will update values on each call, any caching you need would need to be in your code for v2.

**Comment by root75** [comment]
Hi,
Thank you for this library!
I am trying to cancel a temperature set with the set_temperature permanently to return to normal mode.
I have try :  `>>> zone = ec.locations[0]._gateways[0]._control_systems[0].zones["Salon"]
>>> zone.cancel_temp_override()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cancel_temp_override() takes exactly 2 arguments (1 given)
`

the function ask me for 2 arguments, I don't find any info about this.
Can you help ?

**Comment by paulg1** [comment]
Hi root75,

The code below worked for me.

# Zone names and override temperatures for early, end and now commands
# Customise to suit your system
# Zone names must be spelt EXACTLY as they appear on the evotouch controller
# Override temperatures are in the order [early, end, now]

# It would be better to get data from current schedule but this way is easier!

zoneData = {'Lounge': [21.0, 10.0, 21.0],
            'Hall': [20.0, 10.0, 20.0],
            'Bedroom 1': [18.0, 10.0, 10.0],
            'Bedroom 2': [18.0, 10.0, 10.0]}
------------
# Cancel - cancel temperature overrides in all zones
def cancel():
    client = connectV2()
    for z, t in config.zoneData.items():
        print('cancelling override in ' + z)
        zone = client.locations[0]._gateways[0]._control_systems[0].zones[z]
        zone.cancel_temp_override(z)	# zone parameter needed but is not used
        time.sleep(2)
