### ISSUE TITLE
Is it possible to see the status off the heating relay?  BDR91

### ISSUE THREAD

**Issue by FirelightLokeren** [watchforstock/evohome-client#35]
Hi,

I have a atp921r3100 wifi connected display/gataway with 9 zones and 1 BDR91 connected (on/off relay)
All zone and set point are seen/controlled in domoticz, but is it possible to see the status of the relay?

**Comment by watchforstock** [comment]
I don't believe so. The API doesn't supply that information back unfortunately.

**Comment by FirelightLokeren** [comment]
Ok, thx for the answers.

I will try with the hgi80. But i have 1st other things to do


Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Andrew Stock <notifications@github.com> Datum: 21/03/17  17:36  (GMT+01:00) Aan: watchforstock/evohome-client <evohome-client@noreply.github.com> Cc: FirelightLokeren <Koen@firelight.be>, Author <author@noreply.github.com> Onderwerp: Re: [watchforstock/evohome-client] Is it possible to see the status off the heating relay? BDR91 (#35) 
I don't believe so. The API doesn't supply that information back unfortunately.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/watchforstock/evohome-client","title":"watchforstock/evohome-client","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/watchforstock/evohome-client"}},"updates":{"snippets":[{"icon":"PERSON","message":"@watchforstock in #35: I don't believe so. The API doesn't supply that information back unfortunately."}],"action":{"name":"View Issue","url":"https://github.com/watchforstock/evohome-client/issues/35#issuecomment-288138205"}}}
