### ISSUE TITLE
error in evohome/homeassistant

### ISSUE THREAD

**Issue by phsdv** [watchforstock/evohome-client#41]
Each time a temperature setting gets changed an error is thrown and Honeywell sends me an email that an error occurred in 'changing a zone' I reported this in HA (https://github.com/home-assistant/home-assistant/issues/13047). Maybe Honeywell changed something? I am not sure where the error is, HA, evohome or at Honeyell

**Comment by zxdavb** [comment]
@phsdv has reported that this problem has resolved itself at https://github.com/home-assistant/home-assistant/issues/13047 (the issue is now closed there).
