### ISSUE TITLE
Time for a new release? 0.2.7?

### ISSUE THREAD

**Issue by zxdavb** [watchforstock/evohome-client#50]
Home assistant (among others) uses the **evohomeclient** library.  In the case of HA, the `honeywell.py` component uses the v1 api., and has the following line of code:
```
REQUIREMENTS = ['evohomeclient==0.2.5', 'somecomfort==0.5.2']
```

I am about to submit a PR to Homeassistant for an extensively refactored evohome component, `evohome.py`, and it uses v2 of the api, and benefits from the latest changes to **evohomeclient**.  

I am requesting a new release, 0.2.7, so that I can have the following line of code in my component:
```
REQUIREMENTS = ['evohomeclient==0.2.7']
```

**Comment by zxdavb** [comment]
Thanks for that - will it be getting into PyPI too?

**Comment by watchforstock** [comment]
Yes - took me a few minutes to wrestle the right commands, but you should find it there now. Let me know if you find any issues!

**Comment by zxdavb** [comment]
well I can see it in pypi,org, but Home Assistant can't - will give it a day to converge & I'm sure it'll work!

**Comment by zxdavb** [comment]
yep, is working - thanks!
