### ISSUE TITLE
evohomeclient2 changes root logLevel - affects calling module's logLevel

### ISSUE THREAD

**Issue by zxdavb** [watchforstock/evohome-client#51]
The `__init__()` of EvohomeBase has the following code:
```python
if debug:
    logging.getLogger().setLevel(logging.DEBUG)
    ...
else:
    logging.getLogger().setLevel(logging.INFO)
    ...
```
This appears to change the root `logLevel` rather than just that for evohome client.

Maybe something like this would be better:
```python
if debug:
    logging.getLogger(__name__).setLevel(logging.DEBUG)
    ...
else:
    logging.getLogger(__name__).setLevel(logging.INFO)
    ...
```

Reference: https://docs.python.org/3/library/logging.html

**Comment by zxdavb** [comment]
To clarify, I use evohomeclient2 within Home Assistant, and set my own logLevel (as does HA).  When I instantiate the evohomeclient2 client, the root logLevel is changed, thus affecting all HA modules.

**Comment by watchforstock** [comment]
I've made the appropriate change - please let me know if there's an issue

**Comment by zxdavb** [comment]
Yeah, sorry - should have submitted a PR, but I'm a bit overwhelmed with
some other stuff.

Anyway, I will test your change & let you know.

**Comment by zxdavb** [comment]
@watchforstock Sorry to take so long on this, but I can now confirm your fix has resolved the issue.

The v0.2.7 code gives me (where 20 is `logging.INFO`, as set by `base.py`):
```
2018-11-14 22:47:53 WARNING (SyncWorker_11) [homeassistant.components.evohome] before=0, after=20
```
The master branch gives the correct result:
```
2018-11-14 22:37:33 WARNING (SyncWorker_12) [homeassistant.components.evohome] before=0, after=0
```

I have been asked by the HA people to remove the work-around that exists in my component:
```python
        # There's a bug in evohomeclient2 v0.2.7: the client.__init__() sets
        # the root loglevel when EvohomeClient(debug=?), so remember it now...
        log_level = logging.getLogger().getEffectiveLevel()

        client = EvohomeClient(
            evo_data['params'][CONF_USERNAME],
            evo_data['params'][CONF_PASSWORD],
            debug=False
        )
        # ...then restore it to what it was before instantiating the client
        logging.getLogger().setLevel(log_level)
```
You'll understand they're nervous about my code using `logging.getLogger()`!

So, would you kindly consider posting a v0.2.8 to PyPI?
