### ISSUE TITLE
any plans for asyncio version of evohomeclient2?

### ISSUE THREAD

**Issue by zxdavb** [watchforstock/evohome-client#52]
Hi, Are there any plans for asyncio version of evohomeclient2?

**Comment by watchforstock** [comment]
I don't have immediate plans and I haven't heard of anyone who does. That said, if someone wanted to add something to the package that was an asyncio wrapper around the existing library I'd be more than happy to merge it in. Alternatively this could be done as an external package that relies on this one, but that seems like extra effort compared to adding it here.

**Comment by zxdavb** [comment]
Well... I always wanted to learn async io!
