### ISSUE TITLE
Eula issue evohome client version 1

### ISSUE THREAD

**Issue by boe22** [watchforstock/evohome-client#53]
When I try to get the evohome temperatures using version 1, I get the following error:
`  File "evohome.py", line 5, in <module>
    new_dict_list = list(client.temperatures(force_refresh=True))
  File "/usr/local/lib/python2.7/dist-packages/evohomeclient/__init__.py", line 73, in temperatures
    self._populate_full_data(force_refresh)
  File "/usr/local/lib/python2.7/dist-packages/evohomeclient/__init__.py", line 33, in _populate_full_data
    userId = self.user_data['userInfo']['userID']
TypeError: list indices must be integers, not str
`

A bit debugging in `evohomeclient/__init__.py` shows that response.content on line 40 contains: 
`[
  {
    "code": "LatestEulaNotAccepted",
    "message": "Latest Eula is not accepted."
  }
]
`

Furthermore, response.content on line 67 (user_info) shows the following lines (removed others due to privacy):
`{
    "country": "NL",
    "isActivated": true,
    "deviceCount": 0,
    "tenantID": 5,
    "latestEulaAccepted": false
  }
}
`

This all suggests that there should be a EULA accepted at Honeywell before this api can be used. However, within my Honeywell account I cannot find such a button or page. 

Even more strange: evohome client version 2 works perfectly, but I would really like to use version 1 due to the increased accuracy. 

Any clues on how to solve this issue?

**Comment by zxdavb** [comment]
A lot of the original work for this api was done [here](https://www.automatedhome.co.uk/vbulletin/showthread.php?3863-Decoded-EvoHome-API-access-to-control-remotely), and I see no mention of EULA there.

**Comment by boe22** [comment]
Good to know that it is a rare event.

I Figured out a solution: 
a) Remove evohome from evohome account
b) Remove evohome account
c) Create a new account and connect to evohome again. In this second account I chose English as language, not sure if that is relevant. 

The new account works as supposed. 

Although also this second account mentions `"latestEulaAccepted": false` in the `UserInfo`. Weird...

**Comment by nomis** [comment]
This should still be handled because there's nothing worse than an intermittent exception that doesn't explain what went wrong.

**Comment by nomis** [comment]
I created a second account and shared the location with it from the first account.

The second account now gets just the EULA message on the `full_data` part of the process, but the V1 API may not support shared locations.
