### ISSUE TITLE
Error 256

### ISSUE THREAD

**Issue by PatrickSannes** [watchforstock/evohome-client#8]
I'm using your lib in combination with domotocz. I dont know if you have any experience with domotociz? Reading data works like a charm, writing new temps gives an error 256. Do you have any clue how I could get more info about this error to see what is going on?

Patrick

**Comment by watchforstock** [comment]
I would have a look to see if you can turn debugging on when the Evohome client is created. Basically when the EvohomeClient object is created, you can pass debug=True to the constructor and you should get a whole load of extra information printed out.  See if that helps you narrow it down.

**Comment by watchforstock** [comment]
Closing as no follow up so assume it's fixed / being worked around.
