### ISSUE TITLE
While setting new temp on version, I received an error : Error while SetTempE2

### ISSUE THREAD

**Issue by stephane-laurans** [watchforstock/evohome-client#81]
Hi,

First, I would thank you for your overall work on the plugin.

I tried to restore the programmed temperature using the restore button on the widget. Then an error pop up with the message 
Erreur pendant l'envoi de la consigne : Exception - invalid literal for float(): 011null

My configuration:
Plugin version is [version 0.3.2] - 2019-02-18 - fix #7 - the verbose edition
Jeedom Smart with OS version 3.2.16

Hope that it would be useful.

Regards,

**Comment by watchforstock** [comment]
Hi,

You've raised this against the evohome library which, on its own, doesn't have buttons or widgets.  Are you using this with a home automation software? If so which? It's most likely to be an issue with the plugin that uses this library, but obviously if it's traced back to the library please raise an issue here

Andrew

**Comment by watchforstock** [comment]
Closing due to no further comment from OP
